version: "3"

volumes:
    kataszter-mongo-data:
        driver: local

networks:
    mon_go_lang:

services:
    #  _ __ ___     ___    _ __     __ _    ___
    # | '_ ` _ \   / _ \  | '_ \   / _` |  / _ \
    # | | | | | | | (_) | | | | | | (_| | | (_) |
    # |_| |_| |_|  \___/  |_| |_|  \__, |  \___/
    #                               __/ |
    #                              |___/

    kataszter-mongo-db:
        image: mongo:4.2.0-bionic
        container_name: kataszter-mongo-db
        restart: always
        networks:
            - mon_go_lang
        volumes:
            - kataszter-mongo-data:/data

    #  _                      _                         _
    # | |                    | |                       | |
    # | |__     __ _    ___  | | __   ___   _ __     __| |
    # | '_ \   / _` |  / __| | |/ /  / _ \ | '_ \   / _` |
    # | |_) | | (_| | | (__  |   <  |  __/ | | | | | (_| |
    # |_.__/   \__,_|  \___| |_|\_\  \___| |_| |_|  \__,_|

    kataszter-backend:
        image: r.edu.codespring.ro/kataszter/kataszter-backend:develop
        container_name: kataszter-backend
        restart: always
        networks:
            - mon_go_lang
        depends_on:
            - kataszter-mongo-db
        environment:
            - DATABASE_URL=mongodb://kataszter-mongo-db:27017
            - DATABASE_NAME=kataszter
            - DATABASE_IMPORT_TYPE=dev
            - WEB_ACCESS_PORT=:8080
        ports:
            - 8080:8080

    #   __                          _                        _
    #  / _|                        | |                      | |
    # | |_   _ __    ___    _ __   | |_    ___   _ __     __| |
    # |  _| | '__|  / _ \  | '_ \  | __|  / _ \ | '_ \   / _` |
    # | |   | |    | (_) | | | | | | |_  |  __/ | | | | | (_| |
    # |_|   |_|     \___/  |_| |_|  \__|  \___| |_| |_|  \__,_|

    kataszter-web-client:
        image: r.edu.codespring.ro/kataszter/kataszter-web-client:33-alpi-deployment-development
        container_name: kataszter-web-client
        restart: always
        depends_on:
            - kataszter-backend
        ports:
            - 80:80
