apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.backend.name }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.servicePort }}
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ .Values.backend.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.frontend.name }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.servicePort }}
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ .Values.frontend.name }}
